In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
trainingDataset = []
classNumber = 0
img_size = 100
path = "/content/drive/My Drive/dataset"

In [ ]:
import cv2
import numpy as np
import os

The clear() method removes all items from the list.

In [ ]:
trainingDataset.clear()
for folder in (os.listdir(path)):
  print(classNumber)
  fp = os.path.join(path,folder)
  for eachImage in os.listdir(fp):
    imagePath = os.path.join(fp,eachImage)
    img = (cv2.imread(imagePath,cv2.IMREAD_GRAYSCALE))/255
    img = cv2.resize(img, (img_size, img_size))
    trainingDataset.append([img,classNumber])
  classNumber = classNumber + 1

print(len(trainingDataset))
print(len(trainingDataset[0]))
print(trainingDataset[0])

0
1
2
1378
2
[array([[0.63190196, 0.64472549, 0.64843137, ..., 0.40981592, 0.42356617,
        0.42334547],
       [0.63190196, 0.64472549, 0.64843137, ..., 0.39910551, 0.41308577,
        0.4391002 ],
       [0.62066667, 0.64472549, 0.64970588, ..., 0.40432587, 0.41063967,
        0.47648974],
       ...,
       [0.151375  , 0.16581618, 0.1444853 , ..., 0.44932601, 0.42598039,
        0.45694353],
       [0.15794853, 0.13767157, 0.12354167, ..., 0.43009799, 0.46640688,
        0.46220105],
       [0.12835294, 0.10215931, 0.13503677, ..., 0.42127446, 0.39339217,
        0.45390924]]), 0]


Module 'time' is used to handle time-related tasks.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.utils import to_categorical
import pickle
import time

In [ ]:
X = []
Y = []
img_size = 100
np.random.shuffle(trainingDataset)
for features, label in trainingDataset:
    X.append(features)
    Y.append(label)
print(Y)    

[1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 

In [ ]:
X = np.array(X).reshape(-1, img_size, img_size, 1)
Y_binary = to_categorical(Y)
print(Y_binary)

[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
model = Sequential()

model.add(Conv2D(40, (3, 3), input_shape=(100,100,1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(60, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(80, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.3))

model.add(Flatten())

model.add(Dense(100))
model.add(Activation('relu'))
 
model.add(Dense(3))
model.add(Activation('softmax'))

TensorBoard is a tool/dashboard for providing the measurements and visualizations needed during the machine learning workflow.

In [ ]:


model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )

In [ ]:
model.fit(X, Y_binary,
          batch_size = 32,
          epochs=10, validation_split = 0.3)
 

Epoch 1/10
31/31 [==============================] - 20s 619ms/step - loss: 0.7344 - accuracy: 0.5560 - val_loss: 0.6692 - val_accuracy: 0.5966
Epoch 2/10
31/31 [==============================] - 19s 610ms/step - loss: 0.5600 - accuracy: 0.7365 - val_loss: 0.5732 - val_accuracy: 0.6884
Epoch 3/10
31/31 [==============================] - 19s 614ms/step - loss: 0.3401 - accuracy: 0.8620 - val_loss: 0.3923 - val_accuracy: 0.8575
Epoch 4/10
31/31 [==============================] - 19s 610ms/step - loss: 0.2197 - accuracy: 0.9263 - val_loss: 0.2574 - val_accuracy: 0.9082
Epoch 5/10
31/31 [==============================] - 19s 606ms/step - loss: 0.1969 - accuracy: 0.9326 - val_loss: 0.6730 - val_accuracy: 0.6449
Epoch 6/10
31/31 [==============================] - 19s 608ms/step - loss: 0.1654 - accuracy: 0.9440 - val_loss: 0.2296 - val_accuracy: 0.9058
Epoch 7/10
31/31 [==============================] - 19s 605ms/step - loss: 0.1361 - accuracy: 0.9564 - val_loss: 0.2238 - val_accuracy: 0.9179

In [ ]:
def prepare(filepath):
    img_size = 100 
    img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)/255  
    img_resize = cv2.resize(img, (img_size, img_size))  
    return img_resize.reshape(-1, img_size, img_size, 1)

The numpy.argmax() function returns index of the max element of the array

In [ ]:
prediction = model.predict(prepare("/content/drive/My Drive/dataset/test/without_mask.JPG"))
print((prediction))

CATEGORIES = ["With Mask", "Without Mask"]

pred_class = CATEGORIES[np.argmax(prediction)]
print(pred_class)



[[0.10821196 0.8122471  0.07954086]]
Without Mask
